---
title: "Untitled"
output: pdf_document
---
```{r}
importData <- read.csv2("./household_power_consumption.txt")
```
Plot 1
```{r}
subsettedData <- subset(importData,importData$Date== c("1/2/2007","2/2/2007"))
##head(subsettedData)
hist(as.numeric(subsettedData$Global_active_power),col="red",main="Global Active Power",xlab="Global Active Power in kw")
png("plot1.png", width=480, height=480)
dev.off()
```
Plot 2

```{r}

dateAndTime <- strptime(paste(subsettedData$Date, subsettedData$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
plot(dateAndTime,subsettedData$Global_active_power, type="l", xlab="", ylab="Global Active Power in kw")
png("plot2.png", width=480, height=480)
dev.off()
```
Plot 3
```{r}
submeters <- c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
subcolors <- c("black","red","blue")
plot(dateAndTime,subsettedData$Sub_metering_1, type="l",ylab="Energy Submettering",xlab="")
lines(dateAndTime,subsettedData$Sub_metering_2,col="red")
lines(dateAndTime,subsettedData$Sub_metering_3,col="blue")
legend("topright",submeters,lty=1,lwd=2,col=subcolors)
png("plot3.png", width=480, height=480)
dev.off()
```

Plot 4

```{r}

par(mfrow = c(2, 2)) 
##Plot 1
plot(dateAndTime, as.numeric(subsettedData$Global_active_power), type="l", xlab="", ylab="Global Active Power")
##Plot 2
plot(dateAndTime, subsettedData$Voltage, type="l", xlab="Date and Time", ylab="Voltage")
##Plot 3
plot(dateAndTime,subsettedData$Sub_metering_1, type="l",ylab="Energy Submettering",xlab="")
lines(dateAndTime,subsettedData$Sub_metering_2,col="red")
lines(dateAndTime,subsettedData$Sub_metering_3,col="blue")
legend("topright",submeters,lty=1,lwd=2,col=subcolors)
##Plot 4
plot(dateAndTime, subsettedData$Global_reactive_power, type="l",xlab = "Date and Time",ylab="Global Reactive Power")

png("plot4.png", width=480, height=480)
dev.off()
```







