importData <- read.csv2("./household_power_consumption.txt")
subsettedData <- subset(importData,importData$Date== c("1/2/2007","2/2/2007"))
dateAndTime <- strptime(paste(subsettedData$Date, subsettedData$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
submeters <- c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
subcolors <- c("black","red","blue")
plot(dateAndTime,subsettedData$Sub_metering_1, type="l",ylab="Energy Submettering",xlab="")
lines(dateAndTime,subsettedData$Sub_metering_2,col="red")
lines(dateAndTime,subsettedData$Sub_metering_3,col="blue")
legend("topright",submeters,lty=1,lwd=2,col=subcolors)
png("plot3.png", width=480, height=480)
dev.off()
